"""
A "dictionary" data structure with all the
2-letter combinations that do not exist in the file
"""
#text = open("EditedList1.TXT")
NonCombinations = {
    "BQ": "BQ",
    "BZ": "BZ",
    "CF": "CF",
    "CJ": "CJ",
    "CV": "CV",
    "CX": "CX",
    "DX": "DX",
    "FX": "FX",
    "FZ": "FZ",
    "HX": "HX",
    "JB": "JB",
    "JC": "JC",
    "JF": "JF",
    "JG": "JG",
    "JQ": "JQ",
    "JV": "JV",
    "JX": "JX",
    "JZ": "JZ",
    "KQ": "KQ",
    "KZ": "KZ",
    "PQ": "PQ",
    "PX": "PX",
    "QC": "QC",
    "QD": "QD",
    "QG": "QG",
    "QH": "QH",
    "QJ": "QJ",
    "QK": "QK",
    "QL": "QL",
    "QM": "QM",
    "QN": "QN",
    "QP": "QP",
    "QQ": "QQ",
    "QR": "QR",
    "QV": "QV",
    "QX": "QX",
    "QY": "QY",
    "QZ": "QZ",
    "SX": "SX",
    "TX": "TX",
    "VB": "VB",
    "VC": "VC",
    "VF": "VF",
    "VJ": "VJ",
    "VM": "VM",
    "VP": "VP",
    "VT": "VT",
    "VW": "VW",
    "VX": "VX",
    "WQ": "WQ",
    "WX": "WX",
    "XD": "XD",
    "XJ": "XJ",
    "XZ": "XZ",
    "ZJ": "ZJ",
    "ZX": "ZX"
}

